project:
  name: quickstart-data-robot-automl-platform
  owner: quickstart-eng@amazon.com
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
    # - ap-northeast-1
    # - ap-northeast-2
    # - ap-south-1
    # - ap-southeast-1
    # - ap-southeast-2
    # - eu-central-1
    # - eu-north-1
    # - eu-west-2
    # - eu-west-3
    # - sa-east-1
    - us-east-1
    # - us-east-2
    # - us-west-1
    # - us-west-2
    # - ca-central-1
tests:
  default:
   template: ./templates/datarobot-new-vpc-entry.template.yaml
   parameters:
     AvailabilityZones: $[taskcat_genaz_2]
     DRHTTPSetting: 'HTTP'
    #  DRAppName: '' # HTTPS only
    #  DRPredName: '' # HTTPS only
    #  DRZone: '' # HTTPS only
    #  DRS3InstallationBucket: ''
     DRS3CreateBucket: "True"
    #  DRSignedURL: 'https://datarobot-enterprise-releases.s3.amazonaws.com/promoted/7.1.1/dockerized/DataRobot-RELEASE-7.1.1.tar.gz?AWSAccessKeyId=AKIAQ6I23A22NIXIMKVW&Expires=1626361102&Signature=EW2Xc92ztFSU1jB3wTjQnqFbA8o%3D'
     DRSignedURL: 'https://dylanowe-ia.s3.us-west-1.amazonaws.com/quickstart/data-robot/DataRobot-RELEASE-7.1.1.tar'
     DRLbCidr: "0.0.0.0/0"
     RemoteAccessCIDR: "0.0.0.0/0"
     KeyPairName: $[taskcat_getkeypair]
     QSS3KeyPrefix: "quickstart-data-robot-automl-platform/"
     QSS3BucketName: $[taskcat_autobucket]
     QSS3BucketRegion: $[taskcat_current_region]