###########################################################################
#  Copyright 2021 DataRobot Inc. All Rights Reserved.                     #
#                                                                         #
#  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES       #
#  OR CONDITIONS OF ANY KIND, express or implied.                         #
###########################################################################


AWSTemplateFormatVersion: "2010-09-09"
Description: DataRobot CloudFormation stack to create the EC2 instances for the cluster. (qs-1xxxxxxxx)
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into an existing VPC
    Order: "5"
  QSLint:
    Exclusions: [ W9002, W9003, W9006 ]
  cfn-lint:
    config:
      ignore_checks:
        - E9101

Parameters:
  MainStack:
    Type: String
    Description: Name of Main Stack
  S3Bucket:
    Type: String
    Description: CloudFormation repository S3 bucket name
  

Resources: 
  DataRobotIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref DataRobotIAMRole

  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DataRobotIAMPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeInstanceStatus'
              - 'ec2:DescribeImages'
              - 'ec2:CreateImage'
              - 'ec2:CreateSnapshot'
              # - 'elasticloadbalancing:*'
              - 'ssm:DescribeParameters'
              - 'autoscaling:*'
            Resource:
              - '*'

          - Effect: Allow
            Action:
              - 'cloudwatch:PutMetricData'
              - 'cloudwatch:GetMetricData'
              - 'cloudwatch:DescribeAlarmsForMetric'
              - 'cloudwatch:ListDashboards'
              - 'cloudwatch:GetMetricStatistics'
              - 'cloudwatch:GetMetricWidgetImage'
              - 'cloudwatch:ListMetrics'
            Resource:
              - !Sub 'arn:${AWS::Partition}:cloudwatch::*:dashboard/*'


          - Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
              - 's3:Get*'
            Resource:
              - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}'
              - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}/*'
              - !Sub 'arn:${AWS::Partition}:s3:::weswagner-quickstart-dr'
              - !Sub 'arn:${AWS::Partition}:s3:::weswagner-quickstart-dr/*'

          - Effect: Allow
            Action:
              - 'cloudformation:DescribeStacks'
              - 's3:PutObject'
              - 's3:ListBucketMultipartUploads'
              - 's3:AbortMultipartUpload'
              - 's3:ListBucketVersions'
              - 's3:ListBucket'
              - 's3:DeleteObject'
              - 's3:GetBucketLocation'
              - 's3:ReplicateDelete'
              - 's3:ListMultipartUploadParts'
              - 'ssm:PutParameter'
              - 'ssm:GetParameter'
              - 'ssm:DeleteParameter'
            Resource:
              - !Sub arn:${AWS::Partition}:ssm:*:*:parameter/*/datarobot-public-key
              - !Sub arn:${AWS::Partition}:ssm:*:*:parameter/*/datarobot-ami-key
              - !Sub arn:${AWS::Partition}:ssm:*:*:parameter/drami
              - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}'
              - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}/*'
              - !Sub 'arn:${AWS::Partition}:cloudformation:*:*:stack/${MainStack}/*'

          - Effect: Allow
            Action:
              - 'ec2:CreateTags'
            Resource:
              - !Sub arn:${AWS::Partition}:ec2:*:*:volume/*

      Roles:
        - !Ref DataRobotIAMRole      
Outputs:
  EC2InstanceSecurityProfile:
    Description: SecurityGroup settings when using an S3 Bucket
    Value: 
      Ref: InstanceProfile
    Export:
      Name: !Sub '${MainStack}-EC2InstanceSecurityProfile' 
  EC2InstanceSecurityProfileARN:
    Description: SecurityGroup settings when using an S3 Bucket
    Value: !GetAtt InstanceProfile.Arn
    Export:
      Name: !Sub '${MainStack}-EC2InstanceSecurityProfileARN'  