###########################################################################
#  Copyright 2020 DataRobot Inc. All Rights Reserved.                     #
#                                                                         #
#  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES       #
#  OR CONDITIONS OF ANY KIND, express or implied.                         #
###########################################################################
#
# TODO: View CloudFormation Logs in the Console
# https://aws.amazon.com/blogs/devops/view-cloudformation-logs-in-the-console/
# https://s3.amazonaws.com/cloudformation-templates-us-east-1/CloudWatch_Logs.template

AWSTemplateFormatVersion: "2010-09-09"
Description: DataRobot CloudFormation stack to create the EC2 instances for the cluster. (qs-????) 
Parameters:
  IamArn:
    Type: String
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
  KeyPairName:
    Description: Name of an existing public/private key pair. If you do not have one in this AWS Region,
      please create it before continuing. 
    Type: 'AWS::EC2::KeyPair::KeyName'
  MaxModelingNodes:
    Default: '3'
    Description: The number of modelling nodes to allow max.
    Type: String
  PrivateSubnet1ID:
    Description: ID of the private subnets they may be deployed
    Type: 'AWS::EC2::Subnet::Id'
  PrivateSubnet2ID:
    Description: ID of the private subnets they may be deployed
    Type: 'AWS::EC2::Subnet::Id'
  MainStack:
    Type: String

Resources:

  ModelLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateData:
        InstanceType: r5.2xlarge
        ImageId: '{{resolve:ssm:drami:1}}'
        SecurityGroupIds: 
          - !Ref EC2SecurityGroup
        IamInstanceProfile:
          Name: !Ref IamArn
        KeyName: !Ref KeyPairName


  ModelAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1ID
        - !Ref PrivateSubnet2ID
      MinSize: '1'
      MaxSize: !Ref MaxModelingNodes
      Cooldown: '300'
      DesiredCapacity: '1'
      LaunchTemplate: 
        LaunchTemplateId: !Ref ModelLaunchTemplate
        Version: !GetAtt
          - ModelLaunchTemplate
          - LatestVersionNumber
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT60M
      AutoScalingCreationPolicy:
        MinSuccessfulInstancesPercent: 100

  WorkerScaleOutPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref ModelAutoScalingGroup
      ScalingAdjustment: 1

  WorkerScaleInPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref ModelAutoScalingGroup
      ScalingAdjustment: -1

  AlertScaleUp:
    Type: 'AWS::CloudWatch::Alarm'
    DependsOn: ModelAutoScalingGroup
    Properties:
      ActionsEnabled: True
      EvaluationPeriods: 2
      Namespace: 'DataRobot/AutoScaling/Testing'
      MetricName: 'ClusterUtilization'
      Threshold: 2
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref WorkerScaleOutPolicy
      AlarmDescription: 'Alarm if demand for workers exceeds existing capacity for workers'
      TreatMissingData: missing
      Period: 60

  AlertScaleDown:
    Type: 'AWS::CloudWatch::Alarm'
    DependsOn: ModelAutoScalingGroup
    Properties:
      ActionsEnabled: True
      EvaluationPeriods: 20
      Namespace: 'DataRobot/AutoScaling/Testing'
      MetricName: 'ClusterUtilization'
      Threshold: 0.5
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref WorkerScaleInPolicy
      AlarmDescription: 'Alarm if supply of workers exceeds existing demand for workers'
      TreatMissingData: missing
      Period: 60    






 
Outputs:
  ModelAutoScalingGroup:
    Description: Auto Scaling group reference ID.
    Value: !Ref ModelAutoScalingGroup
    Export:
      Name: !Sub '${MainStack}-ModelAutoScalingGroup'
