AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy DataRobot into an existing VPC
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into an existing VPC
    Order: "5"
  QSLint:
    Exclusions: [ W9002, W9003, W9004, W9006 ]
  cfn-lint:
    config:
      ignore_checks:
        - E9101
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network / Install Configurations
        Parameters:
          - VPCID
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - PublicSubnet1ID
          - PublicSubnet2ID
      - Label:
          default: Security Configuration
        Parameters:
          - KeyPairName
      - Label:
          default: DataRobot S3 Install Bucket
        Parameters:
          - DRS3InstallationBucket
          - DRS3CreateBucket
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      PublicSubnet1ID:
        default: Public subnet 1 ID
      PublicSubnet2ID:
        default: Public subnet 2 ID
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      DRS3InstallationBucket:
        default: Bucket Name for DR Install S3 Bucket
      DRS3CreateBucket:
        default: Should Quickstart Create the bucket (select false if it already exists)
      VPCID:
        default: VPC ID  
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      KeyPairName:
        default: Key pair name
Parameters:
  PublicSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: ID of the public subnet in Availability Zone 1 of your existing VPC (e.g., subnet-a0246dcd).
  PublicSubnet2ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: ID of the public subnet in Availability Zone 2 of your existing VPC (e.g., subnet-b1236eea).
  PrivateSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: ID of the private subnet in Availability Zone 1 of your existing VPC (e.g., subnet-fe9a8b32).
  PrivateSubnet2ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: ID of the private subnet in Availability Zone 2 of your existing VPC (e.g., subnet-be8b01ea).
  VPCID:
    Type: "AWS::EC2::VPC::Id"
    Description: ID of your existing VPC (e.g., vpc-0343606e).
  KeyPairName:
    Description: Name of an existing public/private key pair. If you do not have one in this AWS Region,
      please create it before continuing.
    Type: 'AWS::EC2::KeyPair::KeyName'
  DRS3InstallationBucket:
    Default: datarobot-weswagner-east2
    Description:
      Name of the S3 bucket you want to install DataRobot into. It should not be public
      and the account you are running the quickstart will need the ability to assigne
      permissions for access to a role for EC2 instances.
    Type: String
  DRS3CreateBucket:
    Default: "False"
    AllowedValues:
      - "False"
      - "True"
    Description: Choose True if you did not already create a bucket and want it to be created by the quickstart
    Type: String
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription:
      The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: weswagner-quickstart-dr
    Description:
      Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    Type: String
    ConstraintDescription:
      The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/). The prefix should
      end with a forward slash (/).
    Default: templates/
    Description:
      S3 key prefix that is used to simulate a directory for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with 
      a forward slash. See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
  QSS3BucketRegion:
    Default: 'us-west-2'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is 
      hosted. Keep the default Region unless you are customizing the template. 
      Changing this Region updates code references to point to a new Quick Start location. 
      When using your own bucket, specify the Region. 
      See https://aws-quickstart.github.io/option1.html.'
    Type: String

Conditions:
  CreateS3BucketCondition: !Equals 
    - !Ref DRS3CreateBucket
    - "True"

Mappings: 
  RegionMap: 
    us-east-1: 
      "Centos": "ami-01ca03df4a6012157"
    us-east-2: 
      "Centos": "ami-000e7ce4dd68e7a11"
    us-west-2:
      "Centos": "ami-0157b1e4eefd91fd7"
    

Resources:
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-quickstart.s3.amazonaws.com/quickstart-linux-bastion/templates/linux-bastion.template
      Parameters:
        VPCID: !Ref VPCID
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        KeyPairName: !Ref 'KeyPairName'
        BastionInstanceType: t2.micro
        BastionHostName: DRBastion
        NumBastionHosts: 2
        BastionAMIOS: Amazon-Linux2-HVM
        EnableTCPForwarding: 'true'
        QSS3BucketName: aws-quickstart
        QSS3KeyPrefix: quickstart-linux-bastion/
        QSS3BucketRegion: us-east-1
        RemoteAccessCIDR: '0.0.0.0/0'
        VPCID: !Ref VPCID


  S3Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateS3BucketCondition
    Properties:
      AccessControl: Private
      BucketName: !Ref DRS3InstallationBucket

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TimeoutInMinutes: 5
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-securitygroup-template.yaml
      Parameters:
        MainStack: !Ref AWS::StackName
        VpcId: !Ref VPCID
        CidrBlock: 0.0.0.0/0
        ExternalIPAddress: 0.0.0.0/0


  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TimeoutInMinutes: 10
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-iam-template.yaml
      Parameters:
        MainStack: !Ref AWS::StackName
        S3Bucket: !Ref DRS3InstallationBucket
        

  AppNode:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-appnode-template.yaml
      TimeoutInMinutes: 120
      Parameters:
        MainStack: !Ref AWS::StackName
        SubnetId: !Ref PrivateSubnet1ID
        Encrypted: false
        EncryptionKey: ' '
        SSHKey: !Ref KeyPairName
        QSInstallationBucket: weswagner-quickstart-dr
        DRInstallationBucket: !Ref DRS3InstallationBucket
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", Centos]
        DownloadURL: "https://datarobot-enterprise-releases.s3.amazonaws.com/promoted/7.0.2/dockerized/DataRobot-RELEASE-7.0.2.tar.gz?AWSAccessKeyId=AKIAQ6I23A22NIXIMKVW&Expires=1623097218&Signature=3%2BdjrvXa3n5NgBc1Gsi09Vt3Ybk%3D"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-AppNode
        - Key: MainStack
          Value: !Ref AWS::StackName
        - Key: NodeType
          Value: DataRobot
    DependsOn: 
      - IAMStack
      - SecurityStack    


  DedicatedPredictionServerStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: 
      - IAMStack
      - SecurityStack
    Properties:
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-node-template.yaml
      Parameters:
        DataVolumeSize: 100
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", Centos]
        InstallationBucket: !Ref DRS3InstallationBucket
        InstanceType: r5.xlarge
        MainStack: !Ref AWS::StackName
        SSHKey: !Ref KeyPairName
        SubnetId: !Ref PrivateSubnet1ID
        Encrypted: false
        EncryptionKey: ' '
      Tags:
        # DataRobot tags
        - Key: Name
          Value: !Sub ${AWS::StackName}-DedicatedPredictionServer
        - Key: MainStack
          Value: !Ref AWS::StackName
        - Key: NodeType
          Value: DataRobot


  ModelManagementStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: 
      - IAMStack
      - SecurityStack
    Properties:
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-node-template.yaml
      Parameters:
        DataVolumeSize: 100
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", Centos]
        InstallationBucket: !Ref DRS3InstallationBucket
        InstanceType: r5.xlarge
        MainStack: !Ref AWS::StackName
        SSHKey: !Ref KeyPairName
        SubnetId: !Ref PrivateSubnet1ID
        Encrypted: false
        EncryptionKey: ' '
      Tags:
        # DataRobot tags
        - Key: Name
          Value: !Sub ${AWS::StackName}-ModelManagement
        - Key: MainStack
          Value: !Ref AWS::StackName
        - Key: NodeType
          Value: DataRobot


# Configured for 4 workers each, total of 8
  ModelingNode1Stack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: 
      - IAMStack
      - SecurityStack
    Properties:
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-node-template.yaml
      Parameters:
        DataVolumeSize: 100
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", Centos]
        InstallationBucket: !Ref DRS3InstallationBucket
        InstanceType: r5.xlarge
        MainStack: !Ref AWS::StackName
        SSHKey: !Ref KeyPairName
        SubnetId: !Ref PrivateSubnet1ID
        Encrypted: false
        EncryptionKey: ' '
      Tags:
        # DataRobot tags
        - Key: Name
          Value: !Sub ${AWS::StackName}-ModelingNode1
        - Key: MainStack
          Value: !Ref AWS::StackName
        - Key: NodeType
          Value: DataRobot


  ModelingNode2Stack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: 
      - IAMStack
      - SecurityStack
    Properties:
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-node-template.yaml
      Parameters:
        DataVolumeSize: 100
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", Centos]
        InstallationBucket: !Ref DRS3InstallationBucket
        InstanceType: r5.xlarge
        MainStack: !Ref AWS::StackName
        SSHKey: !Ref KeyPairName
        SubnetId: !Ref PrivateSubnet2ID
        Encrypted: false
        EncryptionKey: ' '
      Tags:
        # DataRobot tags
        - Key: Name
          Value: !Sub ${AWS::StackName}-ModelingNode2
        - Key: MainStack
          Value: !Ref AWS::StackName
        - Key: NodeType
          Value: DataRobot


# Added to allow for AutoScaling
  ModelingOnlyNodeStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: 
      - IAMStack
      - SecurityStack
    Properties:
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-node-template.yaml
      Parameters:
        DataVolumeSize: 100
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", Centos]
        InstallationBucket: !Ref DRS3InstallationBucket
        InstanceType: r5.2xlarge
        MainStack: !Ref AWS::StackName
        SSHKey: !Ref KeyPairName
        SubnetId: !Ref PrivateSubnet1ID
        Encrypted: false
        EncryptionKey: ' '
      Tags:
        # DataRobot tags
        - Key: Name
          Value: !Sub ${AWS::StackName}-ModelingOnlyNode
        - Key: MainStack
          Value: !Ref AWS::StackName
        - Key: NodeType
          Value: DataRobot  


# Added to allow for AutoScaling
  DataNodeStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: 
      - IAMStack
      - SecurityStack
    Properties:
      TemplateURL: https://weswagner-quickstart-dr.s3.amazonaws.com/templates/datarobot-node-template.yaml
      Parameters:
        DataVolumeSize: 100
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", Centos]
        InstallationBucket: !Ref DRS3InstallationBucket
        InstanceType: r5.2xlarge
        MainStack: !Ref AWS::StackName
        SSHKey: !Ref KeyPairName
        SubnetId: !Ref PrivateSubnet1ID
        Encrypted: false
        EncryptionKey: ' '
      Tags:
        # DataRobot tags
        - Key: Name
          Value: !Sub ${AWS::StackName}-DataNode
        - Key: MainStack
          Value: !Ref AWS::StackName
        - Key: NodeType
          Value: DataRobot  


Outputs:
  MasterTemplate:
    Description: Master Template Complete
    Value: MasterTemplate





    
    